
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
target 'FreeCampingAustralia' do
    # Pods for RnDiffApp
    pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
    pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
    pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
    pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
    pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/'
    pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
    pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
    pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
    pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

      pod 'AppAuth','~> 1.2.0'
      pod 'GoogleMaps'
        pod 'Firebase'
        pod 'Firebase/Core', '~> 6.3.0'
#        pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
      pod 'react-native-maps', path: '../node_modules/react-native-maps'
      pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
      pod 'RNShare', :path => '../node_modules/react-native-share'
      pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
      pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
      pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
      pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
      pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'



    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'


   pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

    target 'FreeCampingAustraliaTests' do
      inherit! :search_paths
      # Pods for testing
      # pod 'React', :path => '../node_modules/react-native/'
    end
    use_native_modules!

  end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
